### ISSUE TITLE
I found ya

### ISSUE THREAD

**Issue by blackandwhiteclient** [JigsawClient/JigsawClientHomepage#1]
Lol I can have jigsaw website source lolololo xdddd. I found it like this: i went to jigsaw clients wenbsite, than I wanted to download its css, so I wrote /style/style.css .  It gave me a github pages notification about 404 error code. Then I started searching: github.com/jigsawdev, github.com/jigsaw, and than i found github.com/jigsawclient woalalalalala! Next time you should add a custom 404 page, it is easy. Now downloading and posting the link.

**Comment by SenkJu** [comment]
We are not trying to hide the source

**Comment by blackandwhiteclient** [comment]
@robbanrobbin

**Comment by robinkarlberg** [comment]
AHHAHAHAHAHHA

You are kidding right?

**Comment by yario-o** [comment]
@blackandwhiteclient Lol I can have blackandwhiteclient website source lolololo xdddd. I found it like this: i went to your account. Then I clicked in: https://github.com/blackandwhiteclient/blackandwhiteclient woalalalalala! Now downloading and posting the link.

**Comment by freaky767** [comment]
THIS IS FUNNY LMAOOOOO

**Comment by blackandwhiteclient** [comment]
Sorry, this was my old account, someone cracked it and I just got it back. Sorry for everything

**Comment by SenkJu** [comment]
Don't lie. WTF.

**Comment by Envitous** [comment]
very cool
